"""Model changed

Revision ID: 60771c336490
Revises: 374d02b9ca76
Create Date: 2023-09-15 01:38:20.313566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60771c336490"
down_revision = "374d02b9ca76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
