"""First migration

Revision ID: d70d3ba19848
Revises: 60771c336490
Create Date: 2023-09-27 17:07:24.867984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70d3ba19848'
down_revision = '60771c336490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
